// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjXeIZS0VgeMTJQJzgx4Bsd3T7zY8sWNo',
    appId: '1:477394786207:web:a43232aed55fb11dff4faa',
    messagingSenderId: '477394786207',
    projectId: 'technical-test-6c068',
    authDomain: 'technical-test-6c068.firebaseapp.com',
    storageBucket: 'technical-test-6c068.appspot.com',
    measurementId: 'G-RLY7JPF77B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYW5K_QNo3Ev-A5rBzXkmwg3wGmKTTH6Y',
    appId: '1:477394786207:android:a25025c2fcbca0a2ff4faa',
    messagingSenderId: '477394786207',
    projectId: 'technical-test-6c068',
    storageBucket: 'technical-test-6c068.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDA31NcN5SQ8grtX2B74VXo_427RNomoSs',
    appId: '1:477394786207:ios:4358596fdbea0714ff4faa',
    messagingSenderId: '477394786207',
    projectId: 'technical-test-6c068',
    storageBucket: 'technical-test-6c068.appspot.com',
    iosBundleId: 'com.example.fluttert',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDA31NcN5SQ8grtX2B74VXo_427RNomoSs',
    appId: '1:477394786207:ios:6eff995100fa60d7ff4faa',
    messagingSenderId: '477394786207',
    projectId: 'technical-test-6c068',
    storageBucket: 'technical-test-6c068.appspot.com',
    iosBundleId: 'com.example.fluttert.RunnerTests',
  );
}
